name: Production Heads Network
favicon: null
layout_spectrum: 0.99075
typography_spectrum: 0.66642
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fe4125'
    - '#90a4a3'
    - '#111515'
    - '#fe973b'
  brandStrength: 0.6875
  lightness: 0.4670122798997909
  saturation: 0.15154604380950332
  rhythmicContrast: 0.223744846181944
purpose: []
