name: Production Heads Network
favicon: null
layout_spectrum: 0.19287950382567942
typography_spectrum: 0.5068380248267204
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.9910080693662167
  lightness: 0.4670122798997909
  saturation: 0.15154604380950332
  rhythmicContrast: 0.223744846181944
purpose: []
